language: node_js
node_js:
  - "22"

dist: jammy

cache:
  directories:
    - node_modules

script:
  # Fungsi Cek Kerapian Kode 
  - npm run lint
  # Fungsi Cek Logika Kode
  - npm run test
  # npm run build akan dijalankan ketika QC Lint & Test 100%
  - npm run build